name: 更新博客到服务器

on:
  push:
    # push 代码的时候 哪个分支会受到影响 这里是 v1.0.0 分支
    branches:
      # - v1.0.0 # 也可以设置为 main 分支
      - main # 也可以设置为 main 分支

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库 action/checkout获取代码
        uses: actions/checkout@main
      # 安装Node环境

      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@main
        with:
          node-version: lts/*

      # 删除依赖
      - name: 删除依赖
        run: rm -rf node_modules

      - name: 切换源  
        run: npm config set registry https://registry.npm.taobao.org

      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # ARGS: '-rltgoDzvO --delete'
          #SOURCE: 'dist/' # 这是要复制到阿里云静态服务器的文件夹名称
          #REMOTE_HOST: '1.14.103.59' # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          #TARGET: '/root/node-server/' # 打包后的 dist 文件夹将放在 /root/node-server
          ARGS: "-avz --delete"
          SOURCE: ${{ secrets.SOURCE_HOST }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          TARGET: ${{ secrets.TARGET }}
        
      # 上传到腾讯云
      # - name: 发布到腾讯云
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     # 私钥
      #     SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      #     # SCP参数
      #     ARGS: '-avzr --delete'
      #     # 源目录
      #     SOURCE: '.vitepress/dist/'
      #     # 服务器ip
      #     REMOTE_HOST: ${{ secrets.REMOTE_TXHOST }}
      #     # 用户
      #     REMOTE_USER: 'root'
          # 目标地址
          # TARGET: '/var/www/html'
          # TARGET: '/root/demo.zuo11.com'
      # 推送信息到微信
      # - name: 推送信息到微信
      #   uses: easychen/github-action-server-chan@main
      #   with:
      #     sendkey: ${{ secrets.SERVER_J }}
      #     title: '网站更新完毕'